### PR TITLE
Support Laravel 9

### PR DESCRIPTION
**Pull request by usernotnull**
## Reason For Change

Fixes issue when used with Laravel 9.

## Resolves

Issue #84.

### CODE REVIEW

**Comment by kudashevs** [comment]
Hello @usernotnull 

I have a question about this PR. Why just not use `share` alias instead of `Share::class`? I mean, it is bound to the `share` alias in the ShareServiceProvider, so we can just use it. I would like to understand the logic behind your decision, so could you please explain it a little bit?

**Comment by usernotnull** [comment]
@kudashevs sure.
In the upgrade guide to L9, it mentions that:

The getFacadeAccessor method must always return a container binding key. In previous releases of Laravel, this method could return an object instance; however, this behavior is no longer supported. If you have written your own facades, you should ensure that this method returns a container binding string.

The lib was working until I upgraded to L9. After changing the facade accessor to a string key as in this PR, I got it to work.

**Comment by kudashevs** [comment]
> The lib was working until I upgraded to L9. After changing the facade accessor to a string key as in this PR, I got it to work.

I had the same problem. However, I changed it to `return 'share';` because it is the container binding key in this case (in ShareServiceProvider.php we have `$this->app->bind('share', function () ...`). That's why I asked you about your decision :)

Thanks you @usernotnull for your answer, I appreciate it :thumbsup:

**Comment by usernotnull** [comment]
Would you like me to update this branch with 'share' key?

**Comment by usernotnull** [comment]
> PS. I'm not sure which way is better, btw. I see advantages and disadvantages in both of them.

The framework uses both.
IMHO the word 'share' is too broad, and an application may use that same key somewhere else and clash.
So it's probably safer to stick to the class name.

**Comment by jorenvh** [comment]
Thank you @usernotnull for your work on this! I appreciate that you took the time to fix!

I agree that it's better to stick to the class name as well 👍

I'm happy to merge this and tag a new release as soon as all workflows pass.

**Comment by usernotnull** [comment]
@jorenvh done.

I added the test cache to gitignore, and removed windows from the workflow (I aimed to keep older versions of PHP and laravel, but too many excludes to add in the list of os, so instead I just stuck to ubuntu, that's how spatie packages have it in any case :) ).

Also to note, I modified Share class to reset the $html value. This makes the tests pass (which was not an issue before changing the key of the facade accessor 🤷🏼). In any case, all tests green now 👍🏼

**Comment by jorenvh** [comment]
@usernotnull thank you very much sir!

I haven't had time to look at the exact changes yet. Are there any breaking changes and do I need to tag a new major release?

**Comment by usernotnull** [comment]
@jorenvh you're welcome!

No breaking changes. A minor release tag is enough 👍🏼

**Comment by jorenvh** [comment]
Thanks again for you work on this! 👍 I will take a closer look & tag a new release later today or during the weekend

**Review by jorenvh — APPROVED** [review]

**Comment by jorenvh** [comment]
@usernotnull I've just tagged & released version 4.2.0 https://github.com/jorenvh/laravel-share/releases/tag/4.2.0

**Comment by usernotnull** [comment]
@jorenvh Great. Have a great weekend :)

**Pull request merged**
