### PR TITLE
changed translation file source

### PR DESCRIPTION
**Pull request by netfox01**
load translation from the published translation file instead of the package translation file.

### CODE REVIEW

**Comment by jorenvh** [comment]
Are you sure you published the file correctly? According to the docs it should just work https://laravel.com/docs/5.4/packages#translations so please provide a bit more information regarding the problem you are facing.

**Comment by netfox01** [comment]
after I installed the package and published it, I tried to change facebook font awesome icon in the file ```resources\lang\en\laravel-share.php``` but it didn't work, I dug into the code and found out the HTML was being loaded from ```vendor\jorenvanhocht\laravel-share\config\laravel-share.php```  :
```php
// src/Providers/ShareServiceProvider.php

$this->loadTranslationsFrom(__DIR__ . '/../../resources/lang/', 'laravel-share');
```

perfectely it should merge both files content (_resources\lang\en\laravel-share.php_ and  _vendor\jorenvanhocht\laravel-share\config\laravel-share.php_) like you did with config/laravel-share.php files

**Comment by jorenvh** [comment]
According to the docs it should work. Just to be sure, what is the language/locale of your app?

**Comment by netfox01** [comment]
English and French as a default language.

**Comment by jorenvh** [comment]
Can you try by creating a fr version of the language file?

**Comment by netfox01** [comment]
I already have the language file in both folders fr and en, and I changed the icon "fa-facebook-official" to "fa-facebook" in the two files inside the folder , but the first icon is still showing up.

**Comment by jorenvh** [comment]
I'm trying to tackle this issue, it's not working over here. I need a bit more time for this.

When comparing my service provider to the docs it should just work but it doesn't so I'm guessing it has something to do on how I register it in my service provider.

**Comment by jorenvh** [comment]
@netfox01 I published a new release that should fix this issue.

After digging abit further I noticed that package language files should be published to lang/vendor/packageName/lang/file.php and that was not the case for this package ;)

I hope this works out for you.

Note: you should remove the published translation files and republish them using `php artisan vendor:publish`

https://github.com/jorenvh/laravel-share/releases/tag/1.0.2

**Pull request closed without merging**
