### PR TITLE
Implements a method that returns only the built link of the social network

### PR DESCRIPTION
**Pull request by samuelhgf**
This PR implements a method that returns only the built link of the Social Network

In case of using combined it return an array containing all the link of the social networks called

@jorenvh

### CODE REVIEW

**Comment by samuelhgf** [comment]
@jorenvh please look at this PR

**Comment by jorenvh** [comment]
@samuelhgf I took a quick look at your PR the day you created it, and I really appreciate that you took the time to contribute to this package.

However I do not appreciate the fact that you spam me for this, you even searched for my phone number and contact me through whatsapp. This is not considered ok. I maintain this package in my free time, but payed work and clients go first. Hopefully you can understand this.

I'm currently fully booked and have no time to take a closer look at your PR. I will have in a few weeks and I will make some time to look closer at this PR. So please be patient and I will get back to you asap.

Have a nice weekend!

**Comment by samuelhgf** [comment]
Hi, Joren

First of all, my apologies and truly sorry for my behavior, I guarantee that this will not happen again with you or any other person. I fully agree that my actions were completely wrong and I thank you for being gentle. 

And second, thank you for taking your time developing this package, it is really useful and I would love to be part of it. Take a look at my PR at any time, don’t rush about it.

**Comment by samuelhgf** [comment]
Hi, @jorenvh. How are you mate? 

Still too busy? Any prevision to see this PR?

Thanks!

**Comment by jorenvh** [comment]
Hi @samuelhgf 

I'm sorry that I didn't had the time yet, had to shift my planning a bit, but it's on my todo list to take a look and test it real quick myself. To give you an idea, my planning in the coming week is quite full, but the week after that should work for me. 

Thank you for understanding and  your patience

**Review by jorenvh — APPROVED** [review]

**Comment by jorenvh** [comment]
@samuelhgf thank you for your suggestion and work on this feature. I rewrote/renamed a few things to make it more clear.

Thank you for your patience and my apologies that it took this long to get back to you on this. I will tag a new release in a few minutes

**Comment by jorenvh** [comment]
v3.3.0 is now available, enjoy!

**Pull request merged**
